version: '3.5'

services:
  dvotemanager:
    build:
      context: ./
    image: "vocdoni/manager-backend:latest"
    env_file: env
    volumes:
      - "run:/app/run"
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - "postgres"
    networks:
      - postgres

  webmanager:
    image: vocdoni/manager-frontend:latest
    env_file: env
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    build: ./misc/db/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vocdoni}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vocdoni}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    run:
