version: '3.5'

services:
  postgres:
    container_name: postgres_mgr
    container_name: postgres
    build: ./misc/db/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vocdoni}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vocdoni}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_mgr
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@vocdoni.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-vocdoni}
    volumes:
       - ./pgadmin.json:/pgadmin4/servers.json
       - pgadmin:/root/.pgadmin
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:

